from numpy import isin


NA = "N/A"


field_names = {
    "kid": {
        "date": "cod_data",
        "isin": "cod_isin",
        "periodo_detenzione_raccomandato": "cod_rhp",
        "favorable_return": "cod_rsfav_1y",
        "favorable_return_rhp": "cod_rsfav_rhp",
        "indicatore_sintetico_rischio": "cod_sri",
        "moderato_return": "cod_rsmod_1y",
        "moderato_return_rhp": "cod_rsmod_rhp",
        "scenario_morte_1": "cod_smor_1y",
        "scenario_morte_rhp": "cod_smor_rhp",
        "sfavorevole_return": "cod_rssfav_1y",
        "sfavorevole_return_rhp": "cod_rssfav_rhp",
        "stress_return": "cod_rsstr_1y",
        "stress_return_rhp": "cod_rsstr_rhp",
        "incidenza_costo_1": "cod_riy_1y",
        "incidenza_costo_rhp": "cod_riy_rhp",
        "costi_ingresso": "cod_costi_ingresso",
        "costi_uscita": "cod_costi_uscita",
        "commissione_gestione": "cod_commissioni_di_gestione",
        "commissione_transazione": "cod_costi_di_transazione",
        "commissione_performance": "cod_commissioni_di_performance",
        "target_market": "cod_target_market",
    },
    "gkid": {
        "date": "cod_data",
        "isin": "cod_isin",
        "periodo_detenzione_raccomandato": "cod_rhp",
        "favorable_return": "cod_rsfav_1y",
        "favorable_return_rhp": "cod_rsfav_rhp",
        "indicatore_sintetico_rischio_min": "cod_sri_min",
        "indicatore_sintetico_rischio_max": "cod_sri_max",
        "moderato_return": "cod_rsmod_1y",
        "moderato_return_rhp": "cod_rsmod_rhp",
        "scenario_morte_1": "cod_smor_1y",
        "scenario_morte_rhp": "cod_smor_rhp",
        "sfavorevole_return": "cod_rssfav_1y",
        "sfavorevole_return_rhp": "cod_rssfav_rhp",
        "stress_return": "cod_rsstr_1y",
        "stress_return_rhp": "cod_rsstr_rhp",
        "incidenza_costo_eur_1_min": "cod_riy_eur_1_min",
        "incidenza_costo_eur_1_max": "cod_riy_eur_1_max",
        "incidenza_costo_eur_2_min": "cod_riy_eur_2_min",
        "incidenza_costo_eur_2_max": "cod_riy_eur_2_max",
        "incidenza_costo_eur_rhp_min": "cod_riy_eur_rhp_min",
        "incidenza_costo_eur_rhp_max": "cod_riy_eur_rhp_max",
        "incidenza_costo_perc_1_min": "cod_riy_perc_1_min",
        "incidenza_costo_perc_1_max": "cod_riy_perc_1_max",
        "incidenza_costo_perc_2_min": "cod_riy_perc_2_min",
        "incidenza_costo_perc_2_max": "cod_riy_perc_2_max",
        "incidenza_costo_perc_rhp_min": "cod_riy_perc_rhp_min",
        "incidenza_costo_perc_rhp_max": "cod_riy_perc_rhp_max",
        "costi_ingresso_gkid_min": "cod_costi_ingresso_min",
        "costi_ingresso_gkid_max": "cod_costi_ingresso_max",
        "costi_uscita_gkid_min": "cod_costi_uscita_min",
        "costi_uscita_gkid_max": "cod_costi_uscita_max",
        "commissione_gestione_gkid_min": "cod_commissioni_di_gestione_min",
        "commissione_gestione_gkid_max": "cod_commissioni_di_gestione_max",
        "commissione_transazione_gkid_min": "cod_costi_di_transazione_min",
        "commissione_transazione_gkid_max": "cod_costi_di_transazione_max",
        "commissione_performance_gkid_min": "cod_commissioni_di_performance_min",
        "commissione_performance_gkid_max": "cod_commissioni_di_performance_max",
        "target_market": "cod_target_market",
    },
    "certificates": {},
}


renaming = {
    "kid": {
        "file_name": "file_name",
        "date": "Data",
        "isin": "ISIN",
        "periodo_detenzione_raccomandato": "RHP (anni)",
        "favorable_return": "RSFAV 1Y %",
        "favorable_return_rhp": "RSFAV RHP %",
        "indicatore_sintetico_rischio": "SRI",
        "moderato_return": "RSMOD 1Y %",
        "moderato_return_rhp": "RSMOD RHP %",
        "scenario_morte_1": "SMOR 1Y (€)",
        "scenario_morte_rhp": "SMOR RHP (€)",
        "sfavorevole_return": "RSSFAV 1Y %",
        "sfavorevole_return_rhp": "RSSFAV RHP %",
        "stress_return": "RSSTR 1Y %",
        "stress_return_rhp": "RSSTR RHP %",
        "incidenza_costo_1": "RIY 1Y %",
        "incidenza_costo_rhp": "RIY RHP %",
        "costi_ingresso": "Costi ingresso",
        "costi_uscita": "Costi uscita",
        "commissione_gestione": "Commissioni di gestione",
        "commissione_transazione": "Costi di transazione",
        "commissione_performance": "Commissioni di performance",
        "target_market": "Target Market",
        "api_costs": "Costi API",
    },
    "gkid": {
        "file_name": "NOME_FILE",
        "date": "Data",
        "periodo_detenzione_raccomandato": "RHP (anni)",
        "favorable_return": "RSFAV 1Y %",
        "favorable_return_rhp": "RSFAV RHP %",
        "indicatore_sintetico_rischio_min": "SRI MIN",
        "indicatore_sintetico_rischio_max": "SRI MAX",
        "isin": "ISIN",
        "moderato_return": "RSMOD 1Y %",
        "moderato_return_rhp": "RSMOD RHP %",
        "scenario_morte_1": "SMOR 1Y (€)",
        "scenario_morte_rhp": "SMOR RHP (€)",
        "sfavorevole_return": "RSSFAV 1Y %",
        "sfavorevole_return_rhp": "RSSFAV RHP %",
        "stress_return": "RSSTR 1Y %",
        "stress_return_rhp": "RSSTR RHP %",
        "incidenza_costo_eur_1_min": "RIY 1Y EUR MIN",
        "incidenza_costo_eur_1_max": "RIY 1Y EUR MAX",
        "incidenza_costo_eur_2_min": "RIY RHP/2 EUR MIN",
        "incidenza_costo_eur_2_max": "RIY RHP/2 EUR MAX",
        "incidenza_costo_eur_rhp_min": "RIY RHP EUR MIN",
        "incidenza_costo_eur_rhp_max": "RIY RHP EUR MAX",
        "incidenza_costo_perc_1_min": "RIY 1Y % MIN",
        "incidenza_costo_perc_1_max": "RIY 1Y % MAX",
        "incidenza_costo_perc_2_min": "RIY RHP/2 % MIN",
        "incidenza_costo_perc_2_max": "RIY RHP/2 % MAX",
        "incidenza_costo_perc_rhp_min": "RIY RHP % MIN",
        "incidenza_costo_perc_rhp_max": "RIY RHP % MAX",
        "costi_ingresso_gkid_min": "Costi ingresso MIN",
        "costi_ingresso_gkid_max": "Costi ingresso MAX",
        "costi_uscita_gkid_min": "Costi uscita MIN",
        "costi_uscita_gkid_max": "Costi uscita MAX",
        "commissione_gestione_gkid_min": "Commissioni di gestione MIN",
        "commissione_gestione_gkid_max": "Commissioni di gestione MAX",
        "commissione_transazione_gkid_min": "Costi di transazione MIN",
        "commissione_transazione_gkid_max": "Costi di transazione MAX",
        "commissione_performance_gkid_min": "Commissioni di performance MIN",
        "commissione_performance_gkid_max": "Commissioni di performance MAX",
        "target_market": "Target Market",
        "api_costs": "Costi API",
    },
    "leonteq": {
        "data_realizzazione_cedola": "Data di Realizzazione della Cedola",
        "data_pagamento": "Data Pagamento",
        "data_osservazione_cedola": "Data di Osservazione della Cedola",
        "data_pagamento_cedola": "Data di Pagamento della Cedola Condizionale",
        "importo_cedola": "Importo della Cedola Condizionale",
        "giorno_monitoraggio_rimborso": "Giorno di Monitoraggio del Rimborso",
        "sottostante": "Sottostante",
        "tipo": "Tipo",
        "borsa": "Borsa",
        "bloom": "Bloomberg Ticker",
        "isin": "ISIN",
        "fixing_eur": "Fixing in EUR",
        "barriera_eur": "Barriera in EUR",
        "coupon_eur": "Coupon in EUR",
        "livello_barriera": "Livello Barriera %",
        "liv_att_cedola_perc": "Livello Attivazione Cedola %",
        "liv_fixing_iniziale": "Livello Fixing Iniziale %",
        "livello_cap": "Livello Cap %",
        "prezzo": "Prezzo",
        "liv_fix_fin": "Livello Fixing Finale",
        "emittente": "Emittente",
        "data_emissione": "Data Emissione",
        "quotazione": "Quotazione",
        "perf_peg": "Performance Peggiore",
        "inv_min": "Investimento Minimo",
        "garanzia_min_perc": "Garanzia Minima %",
        "valuta": "Valuta del Prodotto",
        "descrizione": "Descrizione",
        "data_fix_ini": "Data Fixing Iniziale",
        "data_negoziazione": "Data Emissione",
        "data_fix_fin": "Data Fixing Finale",
        "liv_fix_ini": "Livello Fixing Iniziale",
        "mod_pagamento": "Modalità Pagamento",
        "tasso_cedola_cond": "Tasso Cedola Condizionato",
        "cedola_garantita_perc": "Cedola Garantita %",
        "rischio_cambio": "Rischio Cambio",
        "importo_rimborso": "Importo di Rimborso Massimo",
        "importo_protezione_capitale": "Importo di Protezione del Capitale",
        "partecipazione": "Partecipazione",
        "callable": "Callable",
        "putable": "Putable",
        "data_rimborso": "Data di Rimborso",
        "periodo": "Periodo",
        "autocallable": "Autocallable",
        "softcallable": "Softcallable",
        "effetto_memoria": "Effetto Memoria",
        "strike_level_perc": "Strike Level %",
        "data_osservazione_autocall": "Data di Osservazione Autocall",
        "data_pagamento_autocall": "Data di Pagamento Autocall",
        "autocall_trigger_lvl": "Autocall Trigger Level %",
        "data_rimborso_cedola": "Data di Rimborso Anticipato",
        "liv_attiv_cedola": "Livello di Attivazione Cedola",
        "liv_attiv_autocall": "Livello di Attivazione Autocall",
    },
    "bnp": {
        "isin": "Codice Isin",
        "description": "Descrizione",
        "currency": "Valuta del prodotto",
        "issuer_desc": "Emittente",
        "strike_date": "Data di Strike",
        "issue_date": "Data di Emissione",
        "expiry_date": "Data di Liquidazione",
        "final_valuation_date": "Data di Valutazione dell'Importo di Liquidazione",
        "leva_cedolare": "Leva Cedolare",
        "nominal": "Importo Nozionale",
        "market": "quotazione",
        "unconditional_protection": "Protezione",
        "protection": "Protezione < 100%",
        "barrier": "Barriera",
        "barrier_type": "Tipo barriera",
        "callable": "Liquidazione Anticipata Facoltativa",
        "autocallable": "Autocallability",
        "unconditional_coupon_min": "Premio/i",
        "conditional_coupon_min": "Premio/i Condizionato/i",
        "memory": "Effetto memoria",
        "autocall": "Scadenza Anticipata Automatica",
        "autocall barrier": "Barriera per la scadenza anticipata",
        "conditional_coupon_barrier": "Barriera/e per il Versamento del Premio/i Condizionato/i",
        "cap": "Livello Cap",
        "airbag": "airbag",
        "issue_price_perc": "Prezzo di Emissione",
        "instrument_isin": "ISIN",
        "instrument_bloombergcode": "Codice Bloomberg",
        "instrument_description": "Sottostante",
        "observation_coupon_date": "Data/e di Valutazione del/i Premio/i Condizionato/i",
        "payment_coupon_date": "Data/e di Pagamento del/i Premio/i",
        "barrier_coupon": "Barriera/e per il Versamento del Premio/i Condizionato/i",
        "unconditional_coupon": "Premio/i",
        "conditional_coupon": "Premio/i Condizionato/i",
        "payment_callable_date": "Data di Liquidazione Anticipata Facoltativa",
        "observation_autocall_date": "Data/e di Valutazione dell'Importo di Liquidazione (rimborso) Anticipato",
        "barrier_autocall": "Barriera/e per la Scadenza Anticipata",
        "payment_autocall_date": "Data di Scadenza Anticipata",
        "value_autocall": "Premio/I di Uscita",
        "periodo_detenzione_raccomandato": "Periodo di detenzione raccomandato",
        "indicatore_sintetico_rischio": "Indicatore sintetico di rischio",
        "importo_minimo": "Importo Minimo",
        "leva_airbag": "Leva Airbag",
    },
    "transform": {
        "costi_totali_min": "incidenza_costo_eur_rhp_min",
        "costi_totali_max": "incidenza_costo_eur_rhp_max",
        "incidenza_min": "incidenza_costo_perc_rhp_min",
        "incidenza_max": "incidenza_costo_perc_rhp_max",
    },
}


column_order = {
    "kid": [
        "file_name",
        "Data",
        "ISIN",
        "RHP (anni)",
        "SRI",
        "RSSTR 1Y %",
        "RSSTR RHP %",
        "RSSFAV 1Y %",
        "RSSFAV RHP %",
        "RSMOD 1Y %",
        "RSMOD RHP %",
        "RSFAV 1Y %",
        "RSFAV RHP %",
        "SMOR 1Y (€)",
        "SMOR RHP (€)",
        "RIY 1Y %",
        "RIY RHP %",
        "Costi ingresso",
        "Costi uscita",
        "Commissioni di gestione",
        "Costi di transazione",
        "Commissioni di performance",
        "Target Market",
        "Costi API",
    ],
    "g-kid": [
        "NOME_FILE",
        "Data",
        "ISIN",
        "RHP (anni)",
        "SRI MIN",
        "SRI MAX",
        "RSSTR 1Y %",
        "RSSTR RHP %",
        "RSSFAV 1Y %",
        "RSSFAV RHP %",
        "RSMOD 1Y %",
        "RSMOD RHP %",
        "RSFAV 1Y %",
        "RSFAV RHP %",
        "SMOR 1Y (€)",
        "SMOR RHP (€)",
        "RIY 1Y % MIN",
        "RIY 1Y % MAX",
        "RIY RHP/2 % MIN",
        "RIY RHP/2 % MAX",
        "RIY RHP % MIN",
        "RIY RHP % MAX",
        "RIY 1Y EUR MIN",
        "RIY 1Y EUR MAX",
        "RIY RHP/2 EUR MIN",
        "RIY RHP/2 EUR MAX",
        "RIY RHP EUR MIN",
        "RIY RHP EUR MAX",
        "Costi ingresso MIN",
        "Costi ingresso MAX",
        "Costi uscita MIN",
        "Costi uscita MAX",
        "Commissioni di gestione MIN",
        "Commissioni di gestione MAX",
        "Costi di transazione MIN",
        "Costi di transazione MAX",
        "Commissioni di performance MIN",
        "Commissioni di performance MAX",
        "Target Market",
        "Costi API",
    ],
}

prepare_json = {
    "basic": """{{
        "file_path":"{path}",
        "extraction_cost":{{
            "total":{total},
            "currency":"EUR",
            "models":{models}
            }}
        }}""",
    "sections": {
        "kid": """
{
    "section0": {
        "name": "Informazioni di base",
        "list": ["cod_data", "cod_isin", "cod_rhp"]
    },
    "section1": {
        "name": "Performance",
        "list": ["cod_rsfav_1y", "cod_rsfav_rhp", "cod_sri", "cod_rsmod_1y", "cod_rsmod_rhp", "cod_smor_1y", "cod_smor_rhp", "cod_rssfav_1y", "cod_rssfav_rhp", "cod_rsstr_1y", "cod_rsstr_rhp"]
    },
    "section2": {
        "name": "Reduction In Yield",
        "list": ["cod_riy_1y", "cod_riy_rhp"]
    },
    "section3": {
        "name": "Costi e Commissioni",
        "list": ["cod_costi_ingresso", "cod_costi_uscita", "cod_commissioni_di_gestione", "cod_costi_di_transazione", "cod_commissioni_di_performance"]
    },
    "section4": {
        "name": "Target Market",
        "list": ["cod_target_market"]
    }
}
""",
        "gkid": """""",
        "certificates": """""",
    },
}

data_array = {
    "kid": [
        "date",
        "isin",
        "periodo_detenzione_raccomandato",
        "favorable_return",
        "favorable_return_rhp",
        "indicatore_sintetico_rischio",
        "moderato_return",
        "moderato_return_rhp",
        "scenario_morte_1",
        "scenario_morte_rhp",
        "sfavorevole_return",
        "sfavorevole_return_rhp",
        "stress_return",
        "stress_return_rhp",
        "incidenza_costo_1",
        "incidenza_costo_rhp",
        "costi_ingresso",
        "costi_uscita",
        "commissione_gestione",
        "commissione_transazione",
        "commissione_performance",
        "target_market",
    ],
    "gkid": [
        "date",
        "isin",
        "periodo_detenzione_raccomandato",
        "favorable_return",
        "favorable_return_rhp",
        "indicatore_sintetico_rischio_min",
        "indicatore_sintetico_rischio_max",
        "moderato_return",
        "moderato_return_rhp",
        "scenario_morte_1",
        "scenario_morte_rhp",
        "sfavorevole_return",
        "sfavorevole_return_rhp",
        "stress_return",
        "stress_return_rhp",
        "incidenza_costo_eur_1_min",
        "incidenza_costo_eur_1_max",
        "incidenza_costo_eur_2_min",
        "incidenza_costo_eur_2_max",
        "incidenza_costo_eur_rhp_min",
        "incidenza_costo_eur_rhp_max",
        "incidenza_costo_perc_1_min",
        "incidenza_costo_perc_1_max",
        "incidenza_costo_perc_2_min",
        "incidenza_costo_perc_2_max",
        "incidenza_costo_perc_rhp_min",
        "incidenza_costo_perc_rhp_max",
        "costi_ingresso_gkid_min",
        "costi_ingresso_gkid_max",
        "costi_uscita_gkid_min",
        "costi_uscita_gkid_max",
        "commissione_gestione_gkid_min",
        "commissione_gestione_gkid_max",
        "commissione_transazione_gkid_min",
        "commissione_transazione_gkid_max",
        "commissione_performance_gkid_min",
        "commissione_performance_gkid_max",
        "target_market",
    ],
}

TRUE = "true"
FALSE = "false"

allow_null = {
    "kid": {
        "date": FALSE,
        "isin": FALSE,
        "periodo_detenzione_raccomandato": FALSE,
        "favorable_return": FALSE,
        "favorable_return_rhp": FALSE,
        "indicatore_sintetico_rischio": FALSE,
        "moderato_return": FALSE,
        "moderato_return_rhp": FALSE,
        "scenario_morte_1": FALSE,
        "scenario_morte_rhp": FALSE,
        "sfavorevole_return": FALSE,
        "sfavorevole_return_rhp": FALSE,
        "stress_return": FALSE,
        "stress_return_rhp": FALSE,
        "incidenza_costo_1": TRUE,
        "incidenza_costo_rhp": FALSE,
        "costi_ingresso": TRUE,
        "costi_uscita": TRUE,
        "commissione_gestione": FALSE,
        "commissione_transazione": FALSE,
        "commissione_performance": TRUE,
        "target_market": FALSE,
    },
    "gkid": {
        "date": FALSE,
        "isin": FALSE,
        "periodo_detenzione_raccomandato": FALSE,
        "favorable_return": FALSE,
        "favorable_return_rhp": FALSE,
        "indicatore_sintetico_rischio_min": FALSE,
        "indicatore_sintetico_rischio_max": FALSE,
        "moderato_return": FALSE,
        "moderato_return_rhp": FALSE,
        "scenario_morte_1": FALSE,
        "scenario_morte_rhp": FALSE,
        "sfavorevole_return": FALSE,
        "sfavorevole_return_rhp": FALSE,
        "stress_return": FALSE,
        "stress_return_rhp": FALSE,
        "incidenza_costo_eur_1_min": TRUE,
        "incidenza_costo_eur_1_max": FALSE,
        "incidenza_costo_eur_2_min": FALSE,
        "incidenza_costo_eur_2_max": FALSE,
        "incidenza_costo_eur_rhp_min": FALSE,
        "incidenza_costo_eur_rhp_max": FALSE,
        "incidenza_costo_perc_1_min": TRUE,
        "incidenza_costo_perc_1_max": FALSE,
        "incidenza_costo_perc_2_min": FALSE,
        "incidenza_costo_perc_2_max": FALSE,
        "incidenza_costo_perc_rhp_min": FALSE,
        "incidenza_costo_perc_rhp_max": FALSE,
        "costi_ingresso_gkid_min": TRUE,
        "costi_ingresso_gkid_max": FALSE,
        "costi_uscita_gkid_min": TRUE,
        "costi_uscita_gkid_max": FALSE,
        "commissione_gestione_gkid_min": FALSE,
        "commissione_gestione_gkid_max": FALSE,
        "commissione_transazione_gkid_min": FALSE,
        "commissione_transazione_gkid_max": FALSE,
        "commissione_performance_gkid_min": TRUE,
        "commissione_performance_gkid_max": FALSE,
        "target_market": FALSE,
    },
}

# extra info for json
INT = "Integer"
FLOAT = "Float"
STRING = "String"


type_of = {
    "kid": {
        "date": "Date",
        "isin": STRING,
        "periodo_detenzione_raccomandato": INT,
        "favorable_return": FLOAT,
        "favorable_return_rhp": FLOAT,
        "indicatore_sintetico_rischio": INT,
        "moderato_return": FLOAT,
        "moderato_return_rhp": FLOAT,
        "scenario_morte_1": FLOAT,
        "scenario_morte_rhp": FLOAT,
        "sfavorevole_return": FLOAT,
        "sfavorevole_return_rhp": FLOAT,
        "stress_return": FLOAT,
        "stress_return_rhp": FLOAT,
        "incidenza_costo_1": FLOAT,
        "incidenza_costo_rhp": FLOAT,
        "costi_ingresso": FLOAT,
        "costi_uscita": FLOAT,
        "commissione_gestione": FLOAT,
        "commissione_transazione": FLOAT,
        "commissione_performance": FLOAT,
        "target_market": STRING,
    },
    "gkid": {
        "date": "Date",
        "isin": STRING,
        "periodo_detenzione_raccomandato": INT,
        "favorable_return": FLOAT,
        "favorable_return_rhp": FLOAT,
        "indicatore_sintetico_rischio_min": INT,
        "indicatore_sintetico_rischio_max": INT,
        "moderato_return": FLOAT,
        "moderato_return_rhp": FLOAT,
        "scenario_morte_1": FLOAT,
        "scenario_morte_rhp": FLOAT,
        "sfavorevole_return": FLOAT,
        "sfavorevole_return_rhp": FLOAT,
        "stress_return": FLOAT,
        "stress_return_rhp": FLOAT,
        "incidenza_costo_eur_1_min": "",
        "incidenza_costo_eur_1_max": FLOAT,
        "incidenza_costo_eur_2_min": FLOAT,
        "incidenza_costo_eur_2_max": FLOAT,
        "incidenza_costo_eur_rhp_min": FLOAT,
        "incidenza_costo_eur_rhp_max": FLOAT,
        "incidenza_costo_perc_1_min": FLOAT,
        "incidenza_costo_perc_1_max": FLOAT,
        "incidenza_costo_perc_2_min": FLOAT,
        "incidenza_costo_perc_2_max": FLOAT,
        "incidenza_costo_perc_rhp_min": FLOAT,
        "incidenza_costo_perc_rhp_max": FLOAT,
        "costi_ingresso_gkid_min": FLOAT,
        "costi_ingresso_gkid_max": FLOAT,
        "costi_uscita_gkid_min": FLOAT,
        "costi_uscita_gkid_max": FLOAT,
        "commissione_gestione_gkid_min": FLOAT,
        "commissione_gestione_gkid_max": FLOAT,
        "commissione_transazione_gkid_min": FLOAT,
        "commissione_transazione_gkid_max": FLOAT,
        "commissione_performance_gkid_min": FLOAT,
        "commissione_performance_gkid_max": FLOAT,
        "target_market": STRING,
    },
}


PERCENT = "%"
EURO = "€"
YEARS = "anni"
CAPS = "CAPS"
model_of = {
    "kid": {
        "date": NA,
        "isin": CAPS,
        "periodo_detenzione_raccomandato": YEARS,
        "favorable_return": PERCENT,
        "favorable_return_rhp": PERCENT,
        "indicatore_sintetico_rischio": YEARS,
        "moderato_return": PERCENT,
        "moderato_return_rhp": PERCENT,
        "scenario_morte_1": EURO,
        "scenario_morte_rhp": EURO,
        "sfavorevole_return": PERCENT,
        "sfavorevole_return_rhp": PERCENT,
        "stress_return": PERCENT,
        "stress_return_rhp": PERCENT,
        "incidenza_costo_1": PERCENT,
        "incidenza_costo_rhp": PERCENT,
        "costi_ingresso": PERCENT,
        "costi_uscita": PERCENT,
        "commissione_gestione": PERCENT,
        "commissione_transazione": PERCENT,
        "commissione_performance": PERCENT,
        "target_market": NA,
    },
    "gkid": {
        "date": NA,
        "isin": CAPS,
        "periodo_detenzione_raccomandato": YEARS,
        "favorable_return": PERCENT,
        "favorable_return_rhp": PERCENT,
        "indicatore_sintetico_rischio_min": YEARS,
        "indicatore_sintetico_rischio_max": YEARS,
        "moderato_return": PERCENT,
        "moderato_return_rhp": PERCENT,
        "scenario_morte_1": EURO,
        "scenario_morte_rhp": EURO,
        "sfavorevole_return": PERCENT,
        "sfavorevole_return_rhp": PERCENT,
        "stress_return": PERCENT,
        "stress_return_rhp": PERCENT,
        "incidenza_costo_eur_1_min": EURO,
        "incidenza_costo_eur_1_max": EURO,
        "incidenza_costo_eur_2_min": EURO,
        "incidenza_costo_eur_2_max": EURO,
        "incidenza_costo_eur_rhp_min": EURO,
        "incidenza_costo_eur_rhp_max": EURO,
        "incidenza_costo_perc_1_min": PERCENT,
        "incidenza_costo_perc_1_max": PERCENT,
        "incidenza_costo_perc_2_min": PERCENT,
        "incidenza_costo_perc_2_max": PERCENT,
        "incidenza_costo_perc_rhp_min": PERCENT,
        "incidenza_costo_perc_rhp_max": PERCENT,
        "costi_ingresso_gkid_min": EURO,
        "costi_ingresso_gkid_max": EURO,
        "costi_uscita_gkid_min": EURO,
        "costi_uscita_gkid_max": EURO,
        "commissione_gestione_gkid_min": PERCENT,
        "commissione_gestione_gkid_max": PERCENT,
        "commissione_transazione_gkid_min": PERCENT,
        "commissione_transazione_gkid_max": PERCENT,
        "commissione_performance_gkid_min": PERCENT,
        "commissione_performance_gkid_max": PERCENT,
        "target_market": NA,
    },
}


decimals_of = {
    "kid": {
        "date": NA,
        "isin": NA,
        "periodo_detenzione_raccomandato": NA,
        "favorable_return": 2,
        "favorable_return_rhp": 2,
        "indicatore_sintetico_rischio": NA,
        "moderato_return": 2,
        "moderato_return_rhp": 2,
        "scenario_morte_1": 2,
        "scenario_morte_rhp": 2,
        "sfavorevole_return": 2,
        "sfavorevole_return_rhp": 2,
        "stress_return": 2,
        "stress_return_rhp": 2,
        "incidenza_costo_1": 2,
        "incidenza_costo_rhp": 2,
        "costi_ingresso": 2,
        "costi_uscita": 2,
        "commissione_gestione": 2,
        "commissione_transazione": 2,
        "commissione_performance": 2,
        "target_market": NA,
    },
    "gkid": {
        "date": None,
        "isin": None,
        "periodo_detenzione_raccomandato": None,
        "favorable_return": 2,
        "favorable_return_rhp": 2,
        "indicatore_sintetico_rischio_min": None,
        "indicatore_sintetico_rischio_max": None,
        "moderato_return": 2,
        "moderato_return_rhp": 2,
        "scenario_morte_1": 2,
        "scenario_morte_rhp": 2,
        "sfavorevole_return": 2,
        "sfavorevole_return_rhp": 2,
        "stress_return": 2,
        "stress_return_rhp": 2,
        "incidenza_costo_eur_1_min": 2,
        "incidenza_costo_eur_1_max": 2,
        "incidenza_costo_eur_2_min": 2,
        "incidenza_costo_eur_2_max": 2,
        "incidenza_costo_eur_rhp_min": 2,
        "incidenza_costo_eur_rhp_max": 2,
        "incidenza_costo_perc_1_min": 2,
        "incidenza_costo_perc_1_max": 2,
        "incidenza_costo_perc_2_min": 2,
        "incidenza_costo_perc_2_max": 2,
        "incidenza_costo_perc_rhp_min": 2,
        "incidenza_costo_perc_rhp_max": 2,
        "costi_ingresso_gkid_min": 2,
        "costi_ingresso_gkid_max": 2,
        "costi_uscita_gkid_min": 2,
        "costi_uscita_gkid_max": 2,
        "commissione_gestione_gkid_min": 2,
        "commissione_gestione_gkid_max": 2,
        "commissione_transazione_gkid_min": 2,
        "commissione_transazione_gkid_max": 2,
        "commissione_performance_gkid_min": 2,
        "commissione_performance_gkid_max": 2,
        "target_market": None,
    },
}


PERCENT_RANGE = []
ISIN_RANGE = []
DATE_RANGE = []

SRI_RANGE = []
NO_RANGE = []

range_of = {
    "kid": {
        "date": DATE_RANGE,
        "isin": ISIN_RANGE,
        "periodo_detenzione_raccomandato": PERCENT_RANGE,
        "favorable_return": PERCENT_RANGE,
        "favorable_return_rhp": PERCENT_RANGE,
        "indicatore_sintetico_rischio": SRI_RANGE,
        "moderato_return": PERCENT_RANGE,
        "moderato_return_rhp": PERCENT_RANGE,
        "scenario_morte_1": NO_RANGE,
        "scenario_morte_rhp": NO_RANGE,
        "sfavorevole_return": PERCENT_RANGE,
        "sfavorevole_return_rhp": PERCENT_RANGE,
        "stress_return": PERCENT_RANGE,
        "stress_return_rhp": PERCENT_RANGE,
        "incidenza_costo_1": PERCENT_RANGE,
        "incidenza_costo_rhp": PERCENT_RANGE,
        "costi_ingresso": PERCENT_RANGE,
        "costi_uscita": PERCENT_RANGE,
        "commissione_gestione": PERCENT_RANGE,
        "commissione_transazione": PERCENT_RANGE,
        "commissione_performance": PERCENT_RANGE,
        "target_market": NO_RANGE,
    },
    "gkid": {
        "date": DATE_RANGE,
        "isin": ISIN_RANGE,
        "periodo_detenzione_raccomandato": PERCENT_RANGE,
        "favorable_return": PERCENT_RANGE,
        "favorable_return_rhp": PERCENT_RANGE,
        "indicatore_sintetico_rischio_min": PERCENT_RANGE,
        "indicatore_sintetico_rischio_max": PERCENT_RANGE,
        "moderato_return": PERCENT_RANGE,
        "moderato_return_rhp": PERCENT_RANGE,
        "scenario_morte_1": NO_RANGE,
        "scenario_morte_rhp": NO_RANGE,
        "sfavorevole_return": PERCENT_RANGE,
        "sfavorevole_return_rhp": PERCENT_RANGE,
        "stress_return": PERCENT_RANGE,
        "stress_return_rhp": PERCENT_RANGE,
        "incidenza_costo_eur_1_min": PERCENT_RANGE,
        "incidenza_costo_eur_1_max": PERCENT_RANGE,
        "incidenza_costo_eur_2_min": PERCENT_RANGE,
        "incidenza_costo_eur_2_max": PERCENT_RANGE,
        "incidenza_costo_eur_rhp_min": PERCENT_RANGE,
        "incidenza_costo_eur_rhp_max": PERCENT_RANGE,
        "incidenza_costo_perc_1_min": PERCENT_RANGE,
        "incidenza_costo_perc_1_max": PERCENT_RANGE,
        "incidenza_costo_perc_2_min": PERCENT_RANGE,
        "incidenza_costo_perc_2_max": PERCENT_RANGE,
        "incidenza_costo_perc_rhp_min": PERCENT_RANGE,
        "incidenza_costo_perc_rhp_max": PERCENT_RANGE,
        "costi_ingresso_gkid_min": PERCENT_RANGE,
        "costi_ingresso_gkid_max": PERCENT_RANGE,
        "costi_uscita_gkid_min": PERCENT_RANGE,
        "costi_uscita_gkid_max": PERCENT_RANGE,
        "commissione_gestione_gkid_min": PERCENT_RANGE,
        "commissione_gestione_gkid_max": PERCENT_RANGE,
        "commissione_transazione_gkid_min": PERCENT_RANGE,
        "commissione_transazione_gkid_max": PERCENT_RANGE,
        "commissione_performance_gkid_min": PERCENT_RANGE,
        "commissione_performance_gkid_max": PERCENT_RANGE,
        "target_market": NO_RANGE,
    },
}
