new_df_renaming = {'Isin': 'isin', 'Descrizione': 'descrizione', 'TipoTitolo': 'tipotitolo', 'Emittente': 'emittente', 'IdEmittente': 'idemittente', 
                   'Divisa': 'divisa', 'Mercato': 'mercato', 'Quotato': 'quotato', 'ValoreNominale': 'valorenominale', 'GaranziaMinimaPerc': 'garanziaminimaperc', 
                   'Garantito': 'garantito', 'ProtezioneCondizionataPerc': 'protezionecondizionataperc', 'BarrieraProtezionePerc': 'barrieraprotezioneperc', 
                   'TipoBarrieraProtezione': 'tipobarrieraprotezione', 'LevaCapitale': 'levacapitale', 'LevaPercCapitale': 'levaperccapitale', 
                   'LevaCedolare': 'levacedolare', 'LevaPercCedolare': 'levaperccedolare', 'CedolaGarantitaPerc': 'cedolagarantitaperc', 
                   'CedolaCondizionataPerc': 'cedolacondizionataperc', 'BarrieraCedolaCondizionataPerc': 'barrieracedolacondizionataperc', 
                   'MemoryCoupon': 'memorycoupon', 'CedolaCapPerc': 'cedolacapperc', 'CodiceSottostante': 'codicesottostante', 
                   'NomeSottostante': 'nomesottostante', 'DivisaSottostante': 'divisasottostante', 'TipoSottostante': 'tiposottostante', 
                   'SottostanteBasket': 'sottostantebasket', 'NumeroSottostanti': 'numerosottostanti', 
                   'Sottostante_1(AnagraficaSottostanti)': 'sottostante_1(anagraficasottostanti)', 
                   'Sottostante_2(AnagraficaSottostanti)': 'sottostante_2(anagraficasottostanti)', 
                   'Sottostante_3(AnagraficaSottostanti)': 'sottostante_3(anagraficasottostanti)', 
                   'Sottostante_4(AnagraficaSottostanti)': 'sottostante_4(anagraficasottostanti)', 
                   'Sottostante_5(AnagraficaSottostanti)': 'sottostante_5(anagraficasottostanti)', 'TipoCalcoloBasketPerf': 'tipocalcolobasketperf', 
                   'SottostanteOpaco': 'sottostanteopaco', 'PosizioneLongShortSuSottostante': 'posizionelongshortsusottostante', 
                   'StrategiaLongShort': 'strategialongshort', 'IsQuanto': 'isquanto', 'PathDependent': 'pathdependent', 
                   'TipoRilevazione': 'tiporilevazione', 'FineCollocamento': 'finecollocamento', 'DataEmissione': 'dataemissione', 'DataScadenza': 'datascadenza', 
                   'AutomaticEarlyRedemption': 'automaticearlyredemption', 'TipoPayoff': 'tipopayoff', 'DataInserimento': 'datainserimento', 
                   'ClasseEUSIPA': 'classeeusipa', 'Tipo_IdEmittente': 'tipo_idemittente', 'BailIn': 'bailin', 'RankingBailIn': 'rankingbailin', 'Strike': 'strike', 
                   'CedolaFloorPerc': 'cedolafloorperc', 'OpenEnd': 'openend', 'Callable': 'callable', 'Putable': 'putable', 'CreditLinked': 'creditlinked', 
                   'Decodifica': 'decodifica', 'Retail': 'retail', 'Defaulted': 'defaulted', 'Note': 'note', 'Fare': 'fare', 'FareBailIn': 'farebailin'}
column_dict = {
    'Isin': ['ISIN', 'ISIN?'],
    'Descrizione': ['Nome del prodotto', 'Nome del prodotto?', 'nome_del_prodotto','description'],
    'Emittente': ['Emittente', 'Emittente?','issuer'],
    'Divisa': ['Valuta', 'Valuta?','specified_currency','Valuta_di_emissione_e_regolamento'],
    'Mercato': ['Quotazione in borsa', 'Quotazione in borsa?', 'quotazione_di_borsa','listing','quotazione'],
    'ValoreNominale': ['Ammontare nominale del prodotto', 'Ammontare nominale del prodotto?', 'ammontare_nominale_del_prodotto','issue_price','valore_nominale'],
    'GaranziaMinimaPerc': ['Pagamento minimo', 'Pagamento minimo?', 'pagamento_minimo','floor_amount','protezione_e_livello_di_protezione'],
    'Protezione': ['protection'],
    'BarrieraProtezionePerc': ['Livello della Barriera', 'Livello della Barriera?','livello_barriera','barrier_level','barriera_e_livello_barriera'],
    'BarrieraProtezionePerc_2': ['Prezzo della Barriera', 'Prezzo della Barriera?','prezzo_barriera','barriera_finale_capitale','barriera_finale_capitale?'],
    'PrezzoEsercizio':  ['Prezzo di Esercizio', 'Prezzo di Esercizio?','prezzo_esercizio','strike_level'],
    'TipoBarrieraProtezione': ['TipologiaBarriera', 'TipologiaBarriera?','barrier_type'],
    'Partecipazione': [],
    'Cedola': ['Cedola', 'Cedola?','additional_conditional_amount','conditional_premio','cedola_digitale_esima','Additional_Conditional_Amount'],
    'CedolaGarantitaPerc': ['Cedola garantita', 'Cedola garantita?', 'cedola_garantita','additional_unconditional_amount', 'premio_garantito_certificato','cedola_garantita'],
    'BarrieraCedolaCondizionataPerc': ['Livello della barriera della cedola', 'Livello della barriera della cedola?','livello_barriera_cedola','barriera_cedola','barriera_cedola?','additional_conditional_amount_payment_level','barrier_premio','soglia_cedola_livello_soglia_cedola','Additional_Conditional_Amount_Payment_Level'],
    'MemoryCoupon': ['Effetto memoria', 'Effetto memoria?', 'effetto_memoria','memory_effect','cedola_memoria','memory_effect'],
    'CedolaCapPerc': ['Pagamento Massimo', 'Pagamento Massimo?','PagamentoMassimo','PagamentoMassimo?','maximum_payment','cap'],
    'Sottostanti': ['Sottostanti','Sottostanti?','Sottostanti_bloomberg','Sottostanti_bloomberg?','underlying','underlying_bloomberg','Sottostante'],
    'SottostantiIsin': ['Sottostanti', 'Sottostanti?','Sottostanti_isin','Sottostanti_isin?','underlying','underlying_isin'],
    'DataEmissione': ['Data_Emissione', 'Data_Emissione?','issue_date'],
    'DataScadenza': ['Data di scadenza', 'Data di scadenza?', 'data_di_scadenza','final_payment_date'],
    'AutomaticEarlyRedemption': ['Estinzione anticipata', 'Estinzione anticipata?','estinzione_anticipata','early_redemtion','rimborso_anticipato','early_redemption'],
    'Callable': ['callable', 'callable?'],
    'Putable': ['putable', 'putable?'],
    'Cedola_Autocall': ['early_redemption_amount'],
    'column_4': [],
    'column_5': [],
}

columns_to_clean = ['ValoreNominale', 'GaranziaMinimaPerc', 'Protezione',
                    'BarrieraProtezionePerc', 'PrezzoEsercizio', 'Cedola',
                    'CedolaGarantitaPerc', 'BarrieraCedolaCondizionataPerc',
                    'CedolaCapPerc', 'Cedola_Autocall']


columns_to_date_convert = ['DataEmissione', 'DataScadenza']
